name: nft_wallet
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  flutter_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  dartz: ^0.10.1
  connectivity_plus: ^2.3.0
  shared_preferences: ^2.0.13
  dio: ^4.0.6
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  dio_http2_adapter: ^2.0.0
  dio_smart_retry: ^1.2.0
  pretty_dio_logger: ^1.1.1
  cached_network_image: ^3.2.0
  local_auth: ^2.0.0
  web3dart: ^2.3.5
  walletconnect_dart: ^0.0.3
  url_launcher: ^6.0.20
  logger: ^1.1.0
  fluttertoast: ^8.0.9
  path_provider: ^2.0.9
  auto_route: ^3.2.4
  collection: ^1.15.0
  flutter_swiper_null_safety: ^1.0.2
  matrix4_transform: ^2.0.1
  simple_animations: ^4.0.1
  flutter_spinkit: ^5.1.0
  decimal: ^2.2.0
  supercharged: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  freezed: ^1.1.1
  mockito: ^5.1.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
